Update to nim 2 x
codex-storage/nim-codex-dht pull request #104
Opened 2024-12-13 08:52 UTC by 2-towns

This PR contains the changes to move to Nim 2.0. 

It is depending on PR of nim-datastore not merged yet.

2025-02-04 18:54 UTC, cskiraly commented
LGTM
@2-towns , can you link the nim-datastore PR this depends on?

2025-02-12 23:53 UTC, emizzle requested changes
We need to get these dependencies unipinned from commits as they prevent leniency when building the dependency graph and has come back to bite us many times.

2025-02-12 23:53 UTC, emizzle commented on codexdht.nimble
> +requires "stew >= 0.2.0"
Usually a good idea to prevent major versions (with breaking changes) from creeping in 
```suggestion
requires "stew >= 0.2.0 & < 0.3.0"
```

2025-02-13 02:41 UTC, emizzle commented
https://github.com/codex-storage/nim-codex-dht/pull/105 amends this branch

2025-02-14 00:59 UTC, emizzle approved these changes

2025-02-14 01:01 UTC, merged